create table if not exists public.source_binaries (
  id bigint generated by default as identity primary key,
  notice_id text not null,
  resource_id text not null,
  document_name text not null,
  sha256 text not null,
  size_bytes bigint not null,
  mime_type text,
  source_url text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(resource_id, sha256)
);

create index if not exists source_binaries_notice_idx on public.source_binaries(notice_id);
create index if not exists source_binaries_resource_idx on public.source_binaries(resource_id);
create index if not exists source_binaries_sha_idx on public.source_binaries(sha256);

create table if not exists public.extraction_runs (
  id uuid primary key default gen_random_uuid(),
  source_binary_id bigint not null references public.source_binaries(id) on delete cascade,
  parser_version text not null,
  status text not null check (status in ('running','complete','failed','review_required')),
  extraction_mode text,
  page_count integer,
  logical_row_count integer not null default 0,
  ocr_page_count integer not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error_text text
);

create unique index if not exists extraction_runs_complete_unique
  on public.extraction_runs(source_binary_id, parser_version)
  where status = 'complete';
create index if not exists extraction_runs_source_idx on public.extraction_runs(source_binary_id, started_at desc);

create table if not exists public.source_rows (
  id bigint generated by default as identity primary key,
  source_binary_id bigint not null references public.source_binaries(id) on delete cascade,
  extraction_run_id uuid not null references public.extraction_runs(id) on delete cascade,
  source_row_id text not null unique,
  page_number integer,
  locator text not null,
  row_type text not null,
  exact_text text not null,
  sort_index integer not null default 0,
  geometry jsonb,
  created_at timestamptz not null default now()
);

create index if not exists source_rows_binary_idx on public.source_rows(source_binary_id, sort_index);
create index if not exists source_rows_run_idx on public.source_rows(extraction_run_id);
create index if not exists source_rows_page_idx on public.source_rows(source_binary_id, page_number);
create index if not exists source_rows_text_fts_idx on public.source_rows using gin (to_tsvector('english', exact_text));

alter table public.source_binaries enable row level security;
alter table public.extraction_runs enable row level security;
alter table public.source_rows enable row level security;

drop policy if exists source_binaries_public_read on public.source_binaries;
create policy source_binaries_public_read on public.source_binaries for select using (true);
drop policy if exists extraction_runs_public_read on public.extraction_runs;
create policy extraction_runs_public_read on public.extraction_runs for select using (true);
drop policy if exists source_rows_public_read on public.source_rows;
create policy source_rows_public_read on public.source_rows for select using (true);

create or replace view public.document_analysis_status as
select
  d.notice_id,
  d.resource_id,
  d.document_name,
  d.document_hash,
  sb.id as source_binary_id,
  sb.sha256,
  sb.size_bytes as analyzed_size_bytes,
  er.id as extraction_run_id,
  er.parser_version,
  er.status as extraction_status,
  er.extraction_mode,
  er.page_count,
  er.logical_row_count,
  er.ocr_page_count,
  er.completed_at
from public.documents d
left join lateral (
  select b.* from public.source_binaries b
  where b.resource_id = d.resource_id
  order by b.last_seen_at desc, b.id desc
  limit 1
) sb on true
left join lateral (
  select r.* from public.extraction_runs r
  where r.source_binary_id = sb.id
  order by (r.status = 'complete') desc, r.started_at desc
  limit 1
) er on true;
