name = "samgovsearch"
main = "samgov-proxy-worker.js"
compatibility_date = "2025-08-01"
workers_dev = true

# Cloudflare Git deploy root directory is workers.
# Touch 2026-06-25 to trigger deployment.
